# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 13:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('type', models.CharField(max_length=1, verbose_name='type de plat')),
                ('difficulte', models.CharField(blank=True, choices=[('1', 'Simple'), ('2', 'Moyen'), ('3', 'Difficile')], max_length=1, verbose_name='difficulte')),
                ('cout', models.IntegerField(blank=True, verbose_name='Coût de la recette')),
                ('temps_prepa', models.DurationField(blank=True, null=True, verbose_name='temps de préparation')),
                ('temps_cuisson', models.DurationField(blank=True, null=True, verbose_name='temps de cuisson')),
                ('temps_repos', models.DurationField(blank=True, null=True, verbose_name='temps de repos')),
                ('valide', models.BooleanField(default=False, verbose_name='validé ?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
