# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_auto_20170518_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='recette',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='commentaire_recette', to='cookbook.Recette'),
            preserve_default=False,
        ),
    ]
