# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_auto_20170624_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapes_recette',
            name='recette',
        ),
        migrations.RemoveField(
            model_name='liste_ingredients',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='liste_ingredients',
            name='recette',
        ),
        migrations.AddField(
            model_name='recette',
            name='etape',
            field=models.TextField(null=True, verbose_name='Etape de la recette'),
        ),
        migrations.AddField(
            model_name='recette',
            name='ingredients',
            field=models.TextField(null=True, verbose_name='Ingrédients de la recette'),
        ),
        migrations.DeleteModel(
            name='Etapes_Recette',
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.DeleteModel(
            name='Liste_Ingredients',
        ),
    ]
