# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0006_auto_20170627_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='type',
            field=models.CharField(choices=[('E', 'Entrée'), ('P', 'Plat principal'), ('D', 'Dessert')], max_length=1, verbose_name='type de plat'),
        ),
    ]
