# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0010_auto_20170627_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecetteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images', verbose_name='Image')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.Recette', verbose_name='Recipe')),
            ],
        ),
    ]
