# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0012_auto_20170627_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetteimage',
            name='recette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.Recette', verbose_name='recette'),
        ),
    ]
