# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0014_auto_20170627_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='temps_cuisson',
            field=models.IntegerField(blank=True, null=True, verbose_name='temps de cuisson'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='temps_prepa',
            field=models.IntegerField(blank=True, null=True, verbose_name='temps de préparation'),
        ),
        migrations.AlterField(
            model_name='recette',
            name='temps_repos',
            field=models.IntegerField(blank=True, null=True, verbose_name='temps de repos'),
        ),
    ]
