# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0015_auto_20170627_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetteimage',
            name='file',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Image'),
        ),
    ]
