# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0016_auto_20170627_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetteimage',
            name='file',
            field=models.ImageField(upload_to='images', verbose_name='Image'),
        ),
    ]
