# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0017_auto_20170627_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recette',
            name='valide',
        ),
    ]
