# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0018_remove_recette_valide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.IntegerField(null=True, verbose_name='Note de la recette'),
        ),
    ]
