# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0019_auto_20170628_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='cout',
            field=models.IntegerField(blank=True, null=True, verbose_name='Coût de la recette'),
        ),
        migrations.AlterField(
            model_name='recetteimage',
            name='file',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Image'),
        ),
    ]
